name: Terraform Plan

on:
  push:
    branches:
      - develop
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/week7

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan